### ISSUE TITLE
Another BeagleBone Black revision number in the wild

### ISSUE THREAD

**Issue by BrianAdams** [RobertCNelson/omap-image-builder#100]
aa5533ee41333335424e4c5430303042

May  have been from an Element14 run

Labeled as a Revision B

**Comment by RobertCNelson** [comment]
@jadonk another one snuck by..

@BrianAdams run this with the wp-grounded on the eeprom  (TP4)

```
wget https://raw.githubusercontent.com/RobertCNelson/boot-scripts/master/device/bone/bbb-eeprom.dump
dd if=bbb-eeprom.dump of=/sys/devices/platform/ocp/44e0b000.i2c/i2c-0/0-0050/eeprom
```

**Comment by jadonk** [comment]
2GB eMMC? Rev B is listed on the wiki: http://elinux.org/Beagleboard:BeagleBoneBlack#Revision_B

**Comment by jadonk** [comment]
@RobertCNelson will support for Rev B be added, since it is valid?

**Comment by RobertCNelson** [comment]
@jadonk @BrianAdams can we get the hexdump version:

```
debian@test-bbb-1:/opt/scripts/tools$ sudo ./version.sh | grep eeprom
eeprom:[A335BNLT0A5A1813BBBK3053]
```
Regards,
