### ISSUE TITLE
ureadahead main process terminated with status 5

### ISSUE THREAD

**Issue by QuickJack** [RobertCNelson/omap-image-builder#101]
It seems that ureadahead does not work. However, it slows down the boot process.

It can be disabled manually:
`
$ sudo systemctl disable ureadahead.service
$ sudo systemctl mask ureadahead.service
`

Is there a way to disable ureadahead by default in the generated images?

**Comment by RobertCNelson** [comment]
@QuickJack i agree!  Yeah we don't have the ubuntu patchset to actually use this feature.

Thanks!
