### ISSUE TITLE
Stretch missing some packages previously in Jessie

### ISSUE THREAD

**Issue by jadonk** [RobertCNelson/omap-image-builder#102]
fbset - despite https://github.com/RobertCNelson/omap-image-builder/blob/master/configs/rcn-ee_console_debian_stretch_armhf.conf#L27

Not sure what else, but I ran into that one.

**Comment by jadonk** [comment]
@RobertCNelson also missing 'ruby'. Even though the ruby library isn't there, many other things depend on ruby---like jekyll.

**Comment by RobertCNelson** [comment]
@jadonk what else uses jekyll?  the bone101 is pre-run thru jekyll at deb creation time so we don't need the jekyll binary installed for that.

**Comment by jadonk** [comment]
less

**Comment by jadonk** [comment]
@RobertCNelson fair enough... I was rebuilding bone101, which is why I was using it. Guess there isn't anything else I'm using it for.
