### ISSUE TITLE
MachineKit is not ready for Kernel 4.4

### ISSUE THREAD

**Issue by saeugetier** [RobertCNelson/omap-image-builder#106]
The current MachineKit version is not ready for Kernel 4.4. Kernel 3.8 should be User instead. Please don't publish any further MachineKit images with Kernel 4.4. 

Reference:
https://groups.google.com/forum/m/#!topic/machinekit/FOntRBEnw-A

**Comment by RobertCNelson** [comment]
@saeugetier okay good to know, i'll mark machinekit as EOL then....

NO ONE is working on it.

You are stuck on the 3.8.x kernel which means Blue, Black Wireless, Green Wireless, PocketBone etc don't work..

If you want my builds in the future, just let me know when you guys port to Xenomai 3.0.x (from the current 2.6.x)..

The LAST 3.8.x based build from me is here:

http://elinux.org/Beagleboard:BeagleBoneBlack_Debian#microSD.2FStandalone:_.28machinekit.29_Based_on_Debian_Jessie_with_3.8.x_kernel

Regards,
