### ISSUE TITLE
Legal implications for commercial use

### ISSUE THREAD

**Issue by QuickJack** [RobertCNelson/omap-image-builder#111]
What are the legal implications of using the generated Ubuntu/ Debian images in a commercial product?

It is possible to get the sources using apt-get source. It should also be possible to write a script to generate a file which includes copyright & license information for all packages. This is required by the GPL and/or other licenses.

**Comment by RobertCNelson** [comment]
@QuickJack 

A few years ago, we made sure to always package up the src via:

```
sed -i -e 's:#deb-src:deb-src:g' /etc/apt/sources.list
apt-get update
mkdir -p /tmp/pkg_src/
cd /tmp/pkg_src/
dpkg -l | tail -n+6 | awk '{print \$2}' | sed "s/:armel//g" | sed "s/:armhf//g" > /tmp/pkg_src/pkg_list
apt-get source --download-only \`cat /tmp/pkg_src/pkg_list\`
cd -
```
It wasn't 100% reliable...

Debian: is pretty clear on this, you can read their notes here:

https://www.debian.org/doc/manuals/debian-faq/ch-redistrib.en.html

Ubuntu: personally i don't use it or follow it enough anymore to say yay/nay...

Regards,
