### ISSUE TITLE
4.14.6-bone-rt-r10  missing wlan for Blue  + pin control issues

### ISSUE THREAD

**Issue by patrickpoirier51** [RobertCNelson/omap-image-builder#112]
Try to make a new Image for the Blue for  ArduPilot Flight controler using latest Debian and rt-4.14

Seems that am335x-boneblue-wl1835.dtsi is missing on 4.14.6-bone- rt-r10 branch so I had this error on startup:
[  406.627162] wlcore: ERROR ELP wakeup timeout!
[  706.627220] wlcore: ERROR ELP wakeup timeout!

So I dtb-rebuild adding the wireless file and adding the adc patch to the blue dts : https://github.com/RobertCNelson/dtb-rebuilder/pull/23/commits/7b4ffd7df1b88d4403aa3a1d929696edf84ddfa7

With this , I have Wireless and ADC :-) 

Here is the info:
git:/opt/scripts/:[968ea66122478e4eedc5b9c785a1671f51572cc3]
eeprom:[A335BNLTBLA21712EL004215]
model:[TI_AM335x_BeagleBone_Blue]
dogtag:[BeagleBoard.org Debian Image 2017-10-10]
bootloader:[microSD-(push-button)]:[/dev/mmcblk0]:[U-Boot 2017.09-00002-g0f3f1c7907]
bootloader:[eMMC-(default)]:[/dev/mmcblk1]:[U-Boot 2017.11-00002-g7b415acfc1]
kernel:[4.14.6-bone-rt-r10]
nodejs:[v6.12.2]
uboot_overlay_options:[enable_uboot_overlays=1]
uboot_overlay_options:[disable_uboot_overlay_video=1]
uboot_overlay_options:[disable_uboot_overlay_audio=1]
uboot_overlay_options:[enable_uboot_cape_universal=1]
pkg:[bb-cape-overlays]:[4.4.20171215.0-0rcnee1~stretch+20171215]
pkg:[bb-wl18xx-firmware]:[1.20170829-0rcnee1~stretch+20170829]
pkg:[firmware-ti-connectivity]:[20170823-1rcnee0~stretch+20170830]
dmesg | grep pinctrl-single
[    0.854748] pinctrl-single 44e10800.pinmux: please update dts to use #pinctrl-cells = <1>
[    0.855070] pinctrl-single 44e10800.pinmux: 142 pins at pa f9e10800 size 568
END

=====pin control =====
Pins = Seems there is some mapping issue. According to message above I need to update dts.
Looking at the Blue DTS, I should see this on p8_15:
https://github.com/RobertCNelson/dtb-rebuilder/blob/4.4-ti/src/arm/am335x-boneblue.dts#L238
pinctrl-names = "pruin_pu", "gpio", "gpio_pu", "gpio_pd", "pruin", "qep", "pruecapin_pu";

 I am missing the pruecap
config-pin -l p8.15
default gpio gpio_pu gpio_pd qep pruin
 
and obviously
config-pin P8_15 pru_ecap
Invalid mode: pru_ecap

====UPDATE== This works== 
 echo pruecapin_pu > /sys/devices/platform/ocp/ocp:P8_15_pinmux/state

**Comment by RobertCNelson** [comment]
@patrickpoirier51 looks like screwed up the irq used by the wl1835 when i submitted to mainline:

https://github.com/RobertCNelson/linux-dev/commit/1b4bec0097a39bd98abff83c683d8bd46679da71

Regards,
