### ISSUE TITLE
Read-only root fs with eMMC flasher

### ISSUE THREAD

**Issue by smithwinston** [RobertCNelson/omap-image-builder#114]
I see the `--ro` option, but when I combine it with `--emmc-flasher`, the resulting image has a split 2GB/2GB flasher image, but what it sets up on the BBB is a single partition (not a split ro/rw partition).

Is there a way to build an eMMC flasher image that during the installation process partitions the BBB eMMC with a read-only root fs and a r/w every-thing-else fs? (it would also be great to be able to specify the size of the r/o root fs).

**Comment by RobertCNelson** [comment]
@smithwinston the "--ro" flag needs some work.  I tested it about a month ago with jessie it didn't work.

For reference, i originally wrote that for the debian squeeze era (2011) and i still have one squeeze device (bb-xm, 3.0.x based kernel)...

Regards,

**Comment by smithwinston** [comment]
@RobertCNelson It does appear to _sort of_ work; here's an `lsblk` of my SD card on a BBB after flashing (with the SD card inserted):

```
NAME         MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
mmcblk1boot0 179:8    0    4M  1 disk 
mmcblk1boot1 179:16   0    4M  1 disk 
mmcblk0      179:24   0 29.7G  0 disk 
├─mmcblk0p1  179:25   0    2G  0 part 
└─mmcblk0p2  179:26   0  1.3G  0 part 
mmcblk1      179:0    0  3.6G  0 disk 
└─mmcblk1p1  179:1    0  3.6G  0 part /
```

You can see `mmcblk0p1` is 2GB and `mmcblk0p2` is 1.3GB (this is a 4GB image).  Obviously when installing to the eMMC on the BBB (see `mmcblk1p1`), the script is not creating the r/o root fs.

Thank you for all the great work you do!
