### ISSUE TITLE
/etc/apt/apt.conf.d/02compress-indexes may need updating due to new behaviour in stretch?

### ISSUE THREAD

**Issue by linuxtim** [RobertCNelson/omap-image-builder#115]
WRT https://github.com/RobertCNelson/omap-image-builder/blame/8e7de51b50a2a9b25d2a37d6a73f9cf69eaa9078/scripts/chroot.sh#L326

... the behaviour in stretch has changed.  With the config as-shipping by omap-image-builder, this now:

- Downloads gziped packaged files (even if more highly compressed formats are available - such as xz)
- Re-compresses them with the lz4 algorithm (lower CPU usage to decompress relatively lower compression than gzip) - see `ls -al /var/lib/apt/lists/`

Here are some alternatives:

`Acquire::GzipIndexes "true"; APT::Compressor::gzip::Cost "40"; Acquire::CompressionTypes::Order { "gz"; "xz"; };`

- Downloads gzip by default (even if more highly compressed formats are available - such as xz)
- Stores as gzip

... this pretty much restores the previous behaviour, but won't fall back to downloading uncompressed lists when the gzip'ed ones are retired (currently the Debian archive mirrors offer uncompressed, gzip, xz lists).

`Acquire::GzipIndexes "true"; APT::Compressor::gzip::Cost "40";`

- Downloads with default preference (currently xz)
- Stores as gzip

`Acquire::GzipIndexes "true"; APT::Compressor::xz::Cost "40";`

- Downloads with default preference (currently xz)
- Stores as xz

The final two are substantially quicker for me when downloading over low bandwidth links...

**Comment by RobertCNelson** [comment]
@linuxtim thanks for the configuration hints!  Initially I was just trying to save space, i've added your last option as a default for stretch+
