### ISSUE TITLE
QEMU is un-reliable, thus no longer supported.

### ISSUE THREAD

**Issue by vijaypanchal** [RobertCNelson/omap-image-builder#118]
QEMU is un-reliable, thus no longer supported.

**Comment by RobertCNelson** [comment]
@vijaypanchal why did you open this issue?

The most common qemu "lockup" occurs when running this single command:

```bash
git clone https://github.com/RobertCNelson/boot-scripts /opt/scripts/ --depth 1
```

Regards,
