### ISSUE TITLE
BBGW not booting with Arago images

### ISSUE THREAD

**Issue by tany5522** [RobertCNelson/omap-image-builder#120]
Hi,
I have created images using Arago build:
The images are:
MLO
U-boot.bin
zImage
dtbs
core-image-base-am335x-evm-20181030062907.rootfs

I have copied the MLO, u-boot.img, uEnv.txt, zImage to the boot partition of the SD
Extract the rootfs to rootfs -partition of the SD

My  uEnv.txt sets the following:

"
bootpart=0:2
bootdir=/boot
bootfile=zImage
console=ttyO0,115200n8
fdtaddr=0x88000000
fdtfile=am335x-bonegreen-wireless.dtb"

But when I insert the SD Card, the board does not boot at all.

Quick help is much appreciated.

Thanks in Advance!

Annapurna.B

**Comment by RobertCNelson** [comment]
@tany5522, Closing, sorry this isn't related to "omap-image-builder", you need to contact the team that developed your Arago build..

Regards,
