### ISSUE TITLE
Bionic: kmod breaks any new images

### ISSUE THREAD

**Issue by jeholliday** [RobertCNelson/omap-image-builder#121]
I noticed recently that any bionic image I built with this script was failing to load any kernel modules at boot time. This can be observed by issuing `lsmod`. A good BBB will list a large number of loaded modules, while an affected BBB will return nothing.

I narrowed the image down to system dependencies either of my host machine or the image by repeating a build of an older version of the script. The old version produced an image that also wouldn't load kernel modules, so the issue has to be because of an update to the packages on my machine or in the image.

Taking, the 2018-09-11 release of Ubuntu 18.04.1 from [here](https://elinux.org/BeagleBoardUbuntu#Ubuntu_.2818.04.1.29) provided a known good image to test with. In the process of debugging, I noticed that `sudo apt-get full-upgrade` resulted in the same behavior as the built image. After trial and error, I've identified kmod as the troublesome package.

**The 2018-09-11 release contains kmod version 24-1ubuntu3rcnee0~bionic+20180515. When upgrading, it automatically selects kmod version 24-1ubuntu3.1. Installing this version causes the issues.** I'm not sure how to change the script to use the correct version because debootstrap appears to automatically select version 24-1ubuntu3.1. Additionally, downgrading doesn't appear to fix the issue.

**Comment by RobertCNelson** [comment]
@jeholliday nice! you found it!!

That now explains this regression i was debugging today:

https://forum.digikey.com/t/beaglebone-black-ubuntu-18-04-nfs-server-issue/2154/8

Background: we patch kmod to support *.xz modules so our kernel footprint is about 1/2 of what it use to be under /lib/modules/.  It's a simple patch as kmod already supports *.xz we just need --use-xz to be passed on configure.  kmod in sid/buster already has this change, it's only the older releases that need a rebuild..

Rebuild right now:

https://github.com/rcn-ee/repos/commit/d4ad3696a578b637e3edaeaa05c568817e276752

Then what i need to do is lock that version of kmod similar to what i had to do with chromium to stop broken armhf builds from leaking into our stable image..

https://github.com/RobertCNelson/omap-image-builder/blob/master/scripts/chroot.sh#L670-L675

Regards,

**Comment by RobertCNelson** [comment]
Rebuild done and rsync'ed to apt repo.. 

```code
sudo apt update ; sudo apt upgrade
```
Should bring in the new kmod and make things work again..

I'll work on an 'apt hold" routine for tomorrow.

Regards,

**Comment by jeholliday** [comment]
I can confirm that the update to kmod has fixed this issue, so I will close this issue.
