### ISSUE TITLE
install python3-libgpiod on iot images

### ISSUE THREAD

**Issue by jadonk** [RobertCNelson/omap-image-builder#124]
Needed for rcpy

**Comment by RobertCNelson** [comment]
fixed with: https://github.com/RobertCNelson/omap-image-builder/commit/f0736fda14c4bf3967bad1914cf3c84c2f74bd00

also out starting with today:

https://rcn-ee.net/rootfs/bb.org/testing/2019-07-21/buster-iot/

Regards,
