### ISSUE TITLE
Add Beaglebone AI config

### ISSUE THREAD

**Issue by kzoltaan** [RobertCNelson/omap-image-builder#126]
Can you add hwpack config for beagelebone ai? And when I build image for bbai with bb.org-debian-buster-console-xm.conf, there is no am5729-beagleboneai.dtb in dtbs directory.
thanks

**Comment by RobertCNelson** [comment]
@kzoltaan a new config isn't needed for the AI, use

```
--dtb am57xx-beagle-x15
```

as it's unified..

Regards,
