### ISSUE TITLE
Wrong ti-cmem-modules package

### ISSUE THREAD

**Issue by drmpeg** [RobertCNelson/omap-image-builder#128]
Just ran ./RootStock-NG.sh -c rcn-ee_console_ubuntu_bionic_armhf on a BeagleBoard-X15 and got this error.

E: Unable to locate package ti-cmem-modules-4.19.94-ti-r36
E: Couldn't find any package by glob 'ti-cmem-modules-4.19.94-ti-r36'
E: Couldn't find any package by regex 'ti-cmem-modules-4.19.94-ti-r36'

I'm guessing it should be ti-cmem-4.16.00.00-modules-4.19.94-ti-rt-r36 instead?

**Comment by RobertCNelson** [comment]
@drmpeg , sorry after pushing these changes today, I ended up going down a rabbit hole of figuring out why my Jenkins test server quit working. So never had time to look at the build looks, Yes, we need to update the cmem.
