### ISSUE TITLE
bb-bbai-firmware postinstall issue

### ISSUE THREAD

**Issue by MMetelko** [RobertCNelson/omap-image-builder#184]
I tried building an image yesterday and ran into this issue.  Where does `/lib/firmware/cypress/cyfmac43455-sdio.txt` get saved to the image - here or in the ti-linux-kernel-dev?  This build worked 11/12 and I see a change in the `repos/bb-bbai-firmware repo.  I debated logging this issue here or in the repos/bb-bbai-firmware repo and decided to go with the upper level one. 

```
Setting up bb-bbai-firmware (1.20211117.1-0~focal+20211117) ...
'/lib/firmware/brcm/brcmfmac43455-sdio.beagleboard.org,am5729-beagleboneai.txt' -> '/lib/firmware/brcm/brcmfmac43455-sdio.txt'
'/lib/firmware/brcm/brcmfmac43455-sdio_am5729-beagleboneai.bin' -> '/lib/firmware/brcm/brcmfmac43455.bin'
'/lib/firmware/brcm/brcmfmac43455-sdio.beagleboard.org,am5729-beagleboneai.txt' -> '/lib/firmware/cypress/cyfmac43455-sdio.txt'
/bin/cp: cannot create regular file '/lib/firmware/cypress/cyfmac43455-sdio.txt': No such file or directory
dpkg: error processing package bb-bbai-firmware (--configure):
 installed bb-bbai-firmware package post-installation script subprocess returned error exit status 1
```

Commit used:  f55e2816bf1135207bd626555ecce369ba220964

**Comment by RobertCNelson** [comment]
Thanks @MMetelko !  Yeah, cypress decided to rename their firmware under a new directory, sorry i didn't catch this when i changed it..

This is for the brcmfmac module on the BBAI:

There new firmware came from:
https://www.cypress.com/documentation/software-and-drivers-archive/wifi-bt-linux-archive?cat=other

Regards,
