### ISSUE TITLE
Will not run from Debian 

### ISSUE THREAD

**Issue by jeanparpaillon** [RobertCNelson/omap-image-builder#203]
When running from Debian `RootStock-NG.sh` fails installing dependancies.

In `scripts/install_dependencies.sh`, it looks for `qemu` package, which is a Ubuntu metapackage and does not exist on Debian.

Depending on `qemu-system-arm` solves the issues on Debian. The package also exists on Ubuntu.

**Comment by RobertCNelson** [comment]
They must have dropped this for Bookworm/Sid.. ;)

https://packages.debian.org/bullseye/qemu

Thanks

**Comment by jeanparpaillon** [comment]
@RobertCNelson actually, they have made it a virtual package (provided by 'qemu-system-*') so it won't be listed with `dpkg -l` neither can be installed through `apt install qemu`

**Comment by jeanparpaillon** [comment]
As far as I know, there is no easy way to check if a virtual package is actually 'installed' :/
https://askubuntu.com/questions/679137/how-to-check-if-a-virtual-package-is-installed

**Comment by jeanparpaillon** [comment]
My bad, this is not even a virtual package, but a dummy one. I have no idea how to deal with that :)

**Comment by RobertCNelson** [comment]
The binary's we really want is..

```
/usr/bin/qemu-arm-static
/usr/bin/qemu-aarch64-static
/usr/bin/qemu-riscv64-static
```

qemu-user-static, should be safe for all 'lts' versions of ubuntu and debian now right?

https://packages.debian.org/unstable/qemu-user-static

Regards,

**Comment by jeanparpaillon** [comment]
tbh, I don't really know the difference between qemu-user-static and other qemu-*-static
From the package name point of view, however, qemu-user-static seems a good fit
