### ISSUE TITLE
Make the booted EMMC behavior configurable

### ISSUE THREAD

**Issue by liberato-whisper** [RobertCNelson/omap-image-builder#207]
I'm not sure the best practice for contributing to this repo, so I've opened both [a PR](https://github.com/RobertCNelson/omap-image-builder/pull/206) and this issue (feel free to close/remove whichever is redundant). Basically I need to be able to create an image that has the uEnv.txt default to disabling the EMMC, and the only way i see to do that is to make the change in the aforementioned PR.

**Comment by RobertCNelson** [comment]
@liberato-whisper nope, looks perfect!

**Comment by liberato-whisper** [comment]
@RobertCNelson thanks for the quick turnaround!
