### ISSUE TITLE
BeagleBone + Custom Kernel (uBoot)

### ISSUE THREAD

**Issue by brnluiz** [RobertCNelson/omap-image-builder#43]
I am trying to put the patches from OSADL on my BeagleBone Black but the problem is that I need a pre-installed system on my SD card. With setup_sdcard, which comes with debian demo image, I couldn't update the uImage (which I already have compiled) or anything like that.

I used the --beagleboard.org-production because then I would have the boot/ partition outside of the rootfs/. I tried to delete the two uEnv.txt files and put the MLO and u-boot.img there instead. At the /rootfs/boot i put the uImag and /dts/am335x-boneblack.dtb. But it didn't worked...

That is someway, with the actual script, that could make it work (putting different uImage, in this case)?

**Comment by mrudulachougule** [comment]
Hi Robert,

I am building file system using build root. before that i was using Ubuntu 16.04 file system maintained by you as  mentioned in below link;
https://eewiki.net/display/linuxonarm/BeagleBone+Black#BeagleBoneBlack-HDMI

As build root does not provide "apt-get" support, i am not able to use bb.org-overlays for lcd dts loading
Could you please share your views how to create Ubuntu filesystem, so that i can customize and maintain for long period.

Kindly share your views.

Thanks,
Mrudula

**Comment by RobertCNelson** [comment]
@mrudulachougule

source is here https://github.com/beagleboard/bb.org-overlays/

Regards,

**Comment by mrudulachougule** [comment]
Hi Robert,

Greetings!! Thank you for sharing source path.


Could you please share your views on generating Ubuntu 16.04 root
fileSystem.

I am working on building root file system for beagle bone black using
Buildroot. Since Buildroot does not support gcc and few packages which
would be required to compile bb.org-overlays
<https://github.com/beagleboard/bb.org-overlays/>. Could you please share
details on creating Ubuntu 16.04 root file system from scratch.

Appreciate your Feedback/ suggestions/ views.

Thanks & regards,
Mrudula

**Comment by RobertCNelson** [comment]
@mrudulachougule buildroot supports gcc..

this repo:

https://github.com/RobertCNelson/omap-image-builder

Generates ubuntu rootfs's

Regards,

**Comment by mrudulachougule** [comment]
Hi Robert,

Thank you for sharing details. You have done great Job!  It's good document
to start with.

I am able to build rootfs using "debootstrap". I want to customize this
rootfs and apt-get installation running on Beaglebone taking more time. So
want to emulate ARM platform on Ubuntu  16.04 using QEMU.

Can I use rootfs which is built using omap-image-builder
<https://github.com/RobertCNelson/omap-image-builder>on QEMU?

When I tried to load rootfs.img which is being created using
omap-image-builder on ubuntu with QEMU

(for your reference the command is "*qemu-system-arm -M versatilepb -cpu
cortex-a8 -m 256 -drive file=rootfs.img,media=disk -kernel vmlinuz -append
'root=/dev/mmcblk0p1 rootwait console=ttyS0 rw*' ")

But not able to get console/ display/ GUI.

Do you have any idea how to load rootfs using QEMU?

Please share your valuable views.

Appreciate your Feedback/ ideas/ Views.

Thanks,
Mrudula - Merry Christmas!!





<https://github.com/RobertCNelson/omap-image-builder>

**Comment by mrudulachougule** [comment]
Hi Robert,

I am working on Qt5 application development. Before that I want to
configure QT5 package for beagle bone board.

I am using *qt-everywhere-opensource-src-5.7.0 *source code and want to
configure / compile the same.

As I am installing packages directly in file system running on SD Card, it
is taking more time.
Can I create virtual environment on Host system and do the same
configuration, just to make this process faster?

Even I am not sure on the packages required for QT5 Configuration. Could
you please share minimal list of packages required to configure

*qt-everywhere-opensource-src-5.7.0.*

*Please share your views.*
Thanks,
Mrudula


On Mon, Dec 26, 2016 at 7:36 PM, Mrudula Chougule <chougulemrudula@gmail.com

**Comment by RobertCNelson** [comment]
@mrudulachougule this is off topic for "omap-image-builder"..

qt-everywhere-opensource-src is not a package in debian, qtbase-opensource-src is available and built:
https://packages.debian.org/source/jessie/qtbase-opensource-src

Regards,

**Comment by mrudulachougule** [comment]
Hi Robert,

Thank you for sharing details. You have done great Job!  It's good document
to start with.

I am able to build rootfs using "debootstrap". I want to customize this
rootfs and apt-get installation running on Beaglebone taking more time. So
want to emulate ARM platform on Ubuntu  16.04 using QEMU.

Can I use rootfs which is built using omap-image-builder
<https://github.com/RobertCNelson/omap-image-builder>on QEMU?

When I tried to load rootfs.img which is being created using
omap-image-builder on ubuntu with QEMU

(for your reference the command is "*qemu-system-arm -M versatilepb -cpu
cortex-a8 -m 256 -drive file=rootfs.img,media=disk -kernel vmlinuz -append
'root=/dev/mmcblk0p1 rootwait console=ttyS0 rw*' ")

But not able to get console/ display/ GUI.

Do you have any idea how to load rootfs using QEMU?

Please share your valuable views.

Appreciate your Feedback/ ideas/ Views.

Thanks,
Mrudula

**Comment by RobertCNelson** [comment]
@mrudulachougule my kernel does not include support for versatile.

Regards,

**Comment by mrudulachougule** [comment]
All right!!

I am having some trouble in customizing your root file system.
I am following steps mentioned in this link
https://github.com/RobertCNelson/omap-image-builder,.

I have created file system for ubuntu xenial. Once
armhf-rootfs-ubuntu-xenial.tar is generated, I'm extracting it to ./rootfs
directory and doing chroot to rootfs (chroot ./rootfs/ /bin/bash)  for
installing LCD and touch screen driver.

After installation of custom packages, I have flashed ./rootfs directory to
Sd Card. I am able to boot up this on beagle bone green but permissions for
"/home/ubuntu " directory are getting changed to root.

Could you please share a way/ methos to customize your rootfs on native /
development system.


Thanks,
Mrudula
