### ISSUE TITLE
RootStock-NG.sh fails when using qemu-arm-static

### ISSUE THREAD

**Issue by sylencecc** [RobertCNelson/omap-image-builder#63]
I'm currently unable to build BBB images on amd64 due to RootStock-NG.sh failing with:

    chroot: failed to run command ‘/bin/sh’: No such file or directory

The reason may be that in `scripts/chroot.sh` the qemu-arm-static binary, which is required when building on a different architecture, is removed from the chroot before the `cleanup_script.sh` was run.

**Comment by RobertCNelson** [comment]
Sorry about that @sylencecc i don't usually test qemu anymore..

Regards,
