### ISSUE TITLE
Bug in scripts/chroot.sh

### ISSUE THREAD

**Issue by sylencecc** [RobertCNelson/omap-image-builder#64]
Hello,

since commit 91f43f7cb2c28e175f51a1e4338082835650293d I can't build the images anymore, because of the following errors:
```
platform-bbb/image-builder/scripts/chroot.sh: 235: [: xarmhf: unexpected operator
platform-bbb/image-builder/scripts/chroot.sh: 235: [: xarmhf: unexpected operator
platform-bbb/image-builder/scripts/chroot.sh: 238: [: xarmhf: unexpected operator
```
The problem seems to be that the comparisons on that line are done with `==` as comparison operator instead of `=`.

**Comment by RobertCNelson** [comment]
Sorry about that, a bashism crept in. ;)
