### ISSUE TITLE
package lists cant be diffed

### ISSUE THREAD

**Issue by mhaberler** [RobertCNelson/omap-image-builder#75]
the package lists in the .conf files cannot be reasonably diffed and massaged by meld

I'd propose to change the habit to transform them from:
````
fasel="apt-transport-https alsa-utils apache2 autoconf automake avahi-daemon bash-completion \
u-boot-tools usb-modeswitch usbutils v4l-utils vim wget wireless-tools \
wpasupplicant wvdial zd1211-firmware"
````
into this:
````
fasel="	\
  	alsa-utils	\
 	apache2	\
  	apt-transport-https	\
  	autoconf	\
  	automake	\
...
 	zd1211-firmware	\
"
````
This Emacs Lisp fragment does the job - mark a region including quotes and hit M-/ - replaces the region with a sorted list of packages, one per line

Emacs lisp: https://github.com/mhaberler/omap-image-builder/commit/a8099e6ed5b7286f8e049d79db8641c8ba2515b6

result: https://github.com/mhaberler/omap-image-builder/commit/e3a0c452c6eaae34028da2693af3cd336fb3fade?diff=unified

**Comment by RobertCNelson** [comment]
Makes perfect sense, I'm on board with it.

**Comment by mhaberler** [comment]
ok, then what I will do is 

- crawl back to your master, and take the liberty to fix up your configs which are relevant to us with this wonderful macro ;) so far they are building fine
- propose a PR
- then massage my configs accordingly

**Comment by mhaberler** [comment]
merged
