### ISSUE TITLE
debian-8.4-iot image lacks ntpdate

### ISSUE THREAD

**Issue by hongquan** [RobertCNelson/omap-image-builder#77]
This image lacks `ntpdate` and `ping` command requires root permission to run.

**Comment by RobertCNelson** [comment]
@hongquan don't use ntpdate, systemd-timesyncd is enabled by default...

https://www.freedesktop.org/software/systemd/man/systemd-timesyncd.service.html

(ntpdate has no clue if the network is 'up' so it errors out on startup, whereas systemd-timesyncd knows when the network is connected..)

ping, it should be enabled...

https://github.com/RobertCNelson/omap-image-builder/blob/master/target/chroot/beagleboard.org-jessie.sh#L179-L193

Regards,

**Comment by hongquan** [comment]
Thanks

**Comment by hankchan** [comment]
when the network is not 'up' on startup,ntpdate may return error date.I've had this kind of problem.
