### ISSUE TITLE
crda package in a few configs, but not all

### ISSUE THREAD

**Issue by marcosscriven** [RobertCNelson/omap-image-builder#80]
I noted some CRDA issues when using @eliasbakken's Kamikazee distro, forked from this repo.

All I needed to do was `apt-get install crda`, and looking through your configs, the `rcn-ee` flavours have this in their `deb_include` list. Is there any reason the others don't?

**Comment by RobertCNelson** [comment]
The package list probably needs to be reviewed and minimized.  Aka, another package depends on cards...
