### ISSUE TITLE
Update bonescript

### ISSUE THREAD

**Issue by jadonk** [RobertCNelson/omap-image-builder#84]
With the download link, I'm not sure how I should update bonescript version to -beta9.

**Comment by RobertCNelson** [comment]
So bonescript's npm package is pre built on a jessie image with nodejs v0.12.x installed via:

https://github.com/rcn-ee/npm-package-bonescript

Regards,

**Comment by RobertCNelson** [comment]
https://github.com/rcn-ee/npm-package-bonescript/commit/87b17b9c86ec3e6b4c46ed4265c67398440ac26e
