### ISSUE TITLE
Disabling all USB Device behavior except for chosen HID class

### ISSUE THREAD

**Issue by ElSordo** [RobertCNelson/omap-image-builder#90]
I'm trying to define an hid device using ConfigFs.  The problem I run into is that when I try to set up the UDC attribute of the device that I have defined, I get a device busy error.

I'm running BBB 4.4.9-ti-r25.

In looking at the output of lsusb, I see a lot of modules that depend on libcomposite.  So, what I would like to do is to remove all of them, e.g., usb_f_acm, g_serial, u_serial, ...  Basically, I only want libcomposite to be loaded.

So how do I tell the boot process not to load these beasties?

-David Glaser

**Comment by RobertCNelson** [comment]
They get loaded by an early ran boot script under: /opt/scripts/boot/

Remove this block:

https://github.com/RobertCNelson/boot-scripts/blob/master/boot/generic-startup.sh#L72-L75

Regards,

**Comment by ElSordo** [comment]
The fixed worked like a charm.
I'm up and running with my hid function.
Thanks

**Comment by ElSordo** [comment]
Worked like a charm

Thanks
