### ISSUE TITLE
beaglebone-universal-io

### ISSUE THREAD

**Issue by bigguiness** [RobertCNelson/omap-image-builder#97]
Is this package available as a .deb or only as the git repo?

It appears to be installed on the wheezy lxde and jessie lxgt images but it is missing on both the console images.

Thanks

**Comment by RobertCNelson** [comment]
i need to package this..

```
git clone https://github.com/cdsteinkuehler/beaglebone-universal-io.git
sudo ln -s `pwd`/beaglebone-universal-io/config-pin /usr/local/bin/
```

**Comment by bigguiness** [comment]
Doesn't it actually need to be built and installed in order for the overlays to be in /lib/firmware?

**Comment by RobertCNelson** [comment]
no it's just a shell script to help interpret /sys/...

**Comment by bigguiness** [comment]
I understand that config-pin is a shell script. But doesn't it need the overlays from the repo?

**Comment by RobertCNelson** [comment]
the overlays are provided by the bb-cape-overlays package.

**Comment by bigguiness** [comment]
Isn't that package only available on the jessie images?

**Comment by RobertCNelson** [comment]
Jessie/Stretch and Xenial
